#!/system/bin/sh

 echo "5 1000000000 66" > /proc/overclock/mpu_opps
 echo "4 720000000 54" > /proc/overclock/mpu_opps
 echo "3 600000000 41" > /proc/overclock/mpu_opps
 echo "2 400000000 34" > /proc/overclock/mpu_opps
 echo "1 250000000 27" > /proc/overclock/mpu_opps


