#!/system/bin/sh

 echo "5 1000000000 66" > /proc/overclock/mpu_opps
 echo "4 720000000 52" > /proc/overclock/mpu_opps
 echo "3 600000000 39" > /proc/overclock/mpu_opps
 echo "2 500000000 32" > /proc/overclock/mpu_opps
 echo "1 250000000 25" > /proc/overclock/mpu_opps


